### ISSUE TITLE
I can't run it

### ISSUE THREAD

**Issue by patatero** [pieterderycke/itunes-export#1]
I tried running it with python 2.7.16, got this error:

```
$ python itunes-export.py 
  File "itunes-export.py", line 22
    def exportPlaylist(playlist: Playlist, parentPath: Path):
                               ^
SyntaxError: invalid syntax
```

Tried python 3.7.7, got this error:

```
$ python3 itunes-export.py
Traceback (most recent call last):
  File "itunes-export.py", line 1, in <module>
    from libpytunes import Library
  File "/Users/hisyam/Desktop/itunes-export-master/libpytunes/__init__.py", line 1, in <module>
    from libpytunes.Library import Library
  File "/Users/hisyam/Desktop/itunes-export-master/libpytunes/Library.py", line 3, in <module>
    from six import PY2
ModuleNotFoundError: No module named 'six'
```

Help please?

**Comment by Andrrison** [comment]
I got the same error trying this today too - and no idea how to fix it. @pieterderycke - any suggestions please?

Thanks
