### ISSUE TITLE
Getting 'ModuleNotFoundError: No module named 'six'

### ISSUE THREAD

**Issue by Andrrison** [pieterderycke/itunes-export#2]
Trying this out on Windows 11, but getting the error ModuleNotFoundError: No module named 'six'.

Any tips on how to fix this?

```
C:\Users\[USERNAME]>cd C:\Users\[USERNAME]\Additional\Code\itunes-export-master

C:\Users\[USERNAME]\Additional\Code\itunes-export-master>python itunes-export.py --output "C:\Users\[USERNAME]\Additional\Code\Playlists"
  File "C:\Users\[USERNAME]\Additional\Code\itunes-export-master\itunes-export.py", line 10
    parser.add_argument("--library", "-l", help="The path to the iTunes Library XML.", default=str(Path.home().joinpath("C:\Users\[USERNAME]\Additional\Code\itunes-export-master\iTunes Library.xml")))
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

C:\Users\[USERNAME]\Additional\Code\itunes-export-master>python itunes-export.py --output "C:\Users\[USERNAME]\Additional\Code\Playlists"
Traceback (most recent call last):
  File "C:\Users\[USERNAME]Additional\Code\itunes-export-master\itunes-export.py", line 1, in <module>
    from libpytunes import Library
  File "C:\Users\[USERNAME]\Additional\Code\itunes-export-master\libpytunes\__init__.py", line 1, in <module>
    from libpytunes.Library import Library
  File "C:\Users\[USERNAME]\Additional\Code\itunes-export-master\libpytunes\Library.py", line 3, in <module>
    from six import PY2
ModuleNotFoundError: No module named 'six'

C:\Users\[USERNAME]\Additional\Code\itunes-export-master>
```

**Comment by Hph1247** [comment]
Six appears to be this: https://pypi.org/project/six/#:~:text=Six%20is%20a%20Python%202,compatible%20on%20both%20Python%20versions.

Have you tried pip installing it?
